In [2]:
print("hello")

hello


In [1]:
#  recurrsion
# fact=1
# n=int(input("enter a number"))
# for i in range(1,n+1):
#     fact =fact*i
# print(fact)

120


In [9]:
s="Manasa is good girl"

for char in s:
    print(char)

M
a
n
a
s
a
 
i
s
 
g
o
o
d
 
g
i
r
l


In [46]:
tup_1.count('a')
tup_1.index("a")

3

In [6]:
tup=("manasa", "lala", "mouni", "kantha")
l1=list(tup)
l1[0]="srinu"
tup=tuple(l1)
print(tup)


('srinu', 'lala', 'mouni', 'kantha')


In [9]:
tup=("manasa", "lala", "mouni", "kantha")
l1=list(tup)
l1.append([12,43, 80])
tup=tuple(l1)
print(tup)

('manasa', 'lala', 'mouni', 'kantha', [12, 43, 80])


In [18]:
tup=("manasa", "lala", "mouni", "kantha")
del tup


In [24]:
tup=("manasa", "lala", "mouni", "kantha")
y=("srinivas",)
tup +=y
print(type(tup))

<class 'tuple'>


In [4]:
tup=("manasa", "lala", "mouni", "kantha")
l3=list(tup)
l3.remove("manasa")
tup=tuple(l3)
print(tup)


('lala', 'mouni', 'kantha')


False

unpack

In [32]:
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry


In [38]:
f= ("jack", "apple", "mango", "papaya"," iceapple")
(yellow,*blue, pink)=f
print(yellow)
print(pink)
print(blue)

jack
 iceapple
['apple', 'mango', 'papaya']


joining tuples  tup2=tup+tup1

In [1]:
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


In [30]:
tup_1[-3]

True

In [31]:
tup_1[5]="manu"

TypeError: 'tuple' object does not support item assignment

In [100]:
l1=["manasa", 12, True, "a", 200, "b"]
l1

['manasa', 12, True, 'a', 200, 'b']

In [101]:
l1[0]=10

In [102]:
l1.append("Lalasa")
l1

[10, 12, True, 'a', 200, 'b', 'Lalasa']

In [103]:
l1.append([1,31,25,83,98])

In [104]:
l1.pop()

[1, 31, 25, 83, 98]

In [18]:
l1[1]="lalu"

In [118]:
dec={"mango":120, "guvav":100, "apple":180, "kiwi":210}
dec

{'mango': 120, 'guvav': 100, 'apple': 180, 'kiwi': 210}

In [21]:
dec.keys()

dict_keys(['mango', 'guvav', 'apple', 'kiwi'])

In [22]:
dec.values()

dict_values([120, 100, 180, 210])

In [39]:
dec

{'mango': 40, 'guvav': 100, 'apple': 180, 'kiwi': 210, 'manago': 90}

In [119]:
dec["mango"]=40

In [30]:
set = {12, "Manasa", 2.26, True}
set

{12, 2.26, 'Manasa', True}

In [107]:
set1= {1,1,1,1,1,1, 39, 29}
set1

{1, 29, 39}

In [114]:
set1.add("lalu")

In [115]:
set1.update(["mounish", 120, "3i+4J"])

In [116]:
set1.pop()

'lalu'

DSA Array

In [2]:
import array

In [13]:
a=array.array('i',(12,13,15,14))
a[0]

12

In [ ]:
#  temp variable
# a=12
# b=20
# temp=0
# temp=a
# a=b
# b=temp
# a,b

a=5
b=20
# a=a^b
# print(a)
# b=a^b
# print(b)
# a=a^b
# a,b
# a=a+b
# b=a-b
# a=a-b
a,b

(20, 5)

[]


In [14]:
import numpy as np

In [ ]:
arr=np.array([[12,15,87,90,54],[10,13,25,18,11]])
print(type(arr))


<class 'numpy.ndarray'>


array([[15, 87, 90],
       [13, 25, 18]])

In [28]:
import numpy as np
arr= np.array([[12,15,16],[90,80,70]])
arr[1][0]

90

In [1]:
import array as myarray

array through array module typecodes are i, f,d,u

In [11]:
arr1=myarray.array("i",[12,42,65,78])
arr2=myarray.array("d",[1.2,5.3,7.8,9.6])
print(arr1.typecode)
print(arr2.typecode)
print(arr1)

i
d
array('i', [12, 42, 65, 78])


In [10]:
print(len(arr1))
print(len(arr2))     

4
4


In [23]:
for i in range(0,len(arr1)):
    print(arr1[i],end=" ")
print("\n")

for i in range(0,len(arr2)):
    print(arr2[i],end=" ")

12 42 65 78 

1.2 5.3 7.8 9.6 

In [66]:
print(list(range(1,100, 5)))



[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]


In [81]:
x=list(range(1,100,4))
nuw_array=myarray.array("i",x)
# to display elemens in an array with out type code
for i in range(0, len(nuw_array)):
    print(nuw_array[i], end=" ")
print("\n")
print(nuw_array[1])    

1 5 9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93 97 

5


In [31]:
#  fibanacci series
a=0
b=1
n=10
print(f"{a} {b}", end=" ")
for i in range(n-2):
    n=a+b
    print(n, end=" ")
    a=b
    b=n
    
    

0 1 1 2 3 5 8 13 21 34 

In [145]:
arr=myarray.array('i', [10,27,35,60,65])
for i in range(0, len(arr)):
    print(arr[i], end=" ")
#  insertng elements in an array     
print("\n")
arr.insert(3,100)
for i in range(0, len(arr)):
    print(arr[i], end=" ")
print("\n")    
# appening a elements in an array
arr.append(120)             
for i in range(0, len(arr)):
    print(arr[i], end=" ")
print("\n")
# updating element in an array
arr[0]=1006 
for i in range(0, len(arr)):
    print(arr[i], end=" ") 
print("\n")
    #  deleting the element from index
arr.pop(3)
for i in range(0, len(arr)):
    print(arr[i], end=" ")
print("\n")  
# remove helps in removing the element like 35 
arr.remove(35)
for i in range(0, len(arr)):
    print(arr[i], end=" ")


    

10 27 35 60 65 

10 27 35 100 60 65 

10 27 35 100 60 65 120 

1006 27 35 100 60 65 120 

1006 27 35 60 65 120 

1006 27 60 65 120 

In [2]:
import array as myarray

In [51]:
x=list(range(0,100,3))
arr=myarray.array("i",x)
for i in arr:
    print(i, end=", ")
# print(len(arr))

0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 

In [52]:
# for i in range(0, len(arr[1:10])):
#     print(arr[i], end=" ")
# print("\n")
'''  search a 99 number in an array and its index number'''
index=arr.index(99) 
print(index)
res=arr[index]   
print(res,index)


33
99 33


In [15]:
arr2=arr[10:25]
for i in range(0,len(arr2)):
    print(arr2[i], end=" ")
print("\n")

arr3=arr[10:-10] 
for i in range(0, len(arr3)):
    print(arr3[i], end=" ")
print("\n")

arr4=arr[::-1] 
for i in range(0, len(arr4)):
    print(arr4[i], end=" ")                
                 

0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 



95 90 85 80 75 70 65 60 55 50 45 40 35 30 25 20 15 10 5 0 

Sortin an array ascending anf descending

In [35]:
arr0=myarray.array("i",[10,23,1,76,98,32,11])
arr8=arr0.tolist()

In [38]:
# asecnding order
arr8.sort()
arr8

[1, 10, 11, 23, 32, 76, 98]

In [40]:
# desccending order
arr8.sort(reverse=True)
arr8

[98, 76, 32, 23, 11, 10, 1]

In [43]:
import  numpy as np
import random

In [10]:
a=np.ones((2,2))
print(a,"\n")

b=np.zeros((2,2))
print(b,"\n")

c=np.full((2,2),10)
print(c,"\n")

d=np.eye(4)
print(d,"\n")

e=np.random.random((2,3))
print(e)

[[1. 1.]
 [1. 1.]] 

[[0. 0.]
 [0. 0.]] 

[[10 10]
 [10 10]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[0.55857731 0.18368989 0.2209893 ]
 [0.38843635 0.10430091 0.57843762]]


In [9]:
print(np.array(1),"\n")
print(np.array([12,13,251]),'\n')
print(np.array([[12,32,17],[10,20,30]]),"\n")
print(np.array([[1,2,3],[12,32,43],[90,80,70]]),"\n")

1 

[ 12  13 251] 

[[12 32 17]
 [10 20 30]] 

[[ 1  2  3]
 [12 32 43]
 [90 80 70]] 



In [7]:
arr=np.array([12,32,80,65,48,43,90])
for i in range(0, len(arr)):
    print(arr[i],end=" ")
print('\n')    
    
arr[4]=1000    
for i in range(0, len(arr)):
    print(arr[i],end=" ")
print('\n')

a=np.delete(arr,6)
for i in range(0, len(a)):
    print(a[i],end=" ")
print('\n')

12 32 80 65 48 43 90 

12 32 80 65 1000 43 90 

12 32 80 65 1000 43 



searching in numpy 

In [8]:
p=np.array([12,32,90,776,49,1000])
print(p,"\n")
ab=np.where(p==1000)
print(ab)
# searching 1000 index is 5
print(p[5])


print(np.sort(a))

[  12   32   90  776   49 1000] 

(array([5], dtype=int64),)
1000
[  12   32   43   65   80 1000]


In [5]:
x=np.array([12,31,76,90])
y=np.array([10,20,30,40])


print(np.add(x,y),"\n")
print(np.subtract(x,y),"\n")
print(np.multiply(x,y),"\n")
print(np.divide(x,y),"\n")
print(np.sqrt(x),"\n")

z=np.array([[1,2,3,4],[12,13,14,15],[10,20,30,40]])
# row to column and column to row
print(np.transpose(z))


[ 22  51 106 130] 

[ 2 11 46 50] 

[ 120  620 2280 3600] 

[1.2        1.55       2.53333333 2.25      ] 

[3.46410162 5.56776436 8.71779789 9.48683298] 

[[ 1 12 10]
 [ 2 13 20]
 [ 3 14 30]
 [ 4 15 40]]


Stack emplementation with list tc=o(n)

In [39]:
stack=[]
stack.append(10)
stack.append(29)
stack.append(100)

stack.append(102)
stack.pop()
stack
# to see topmost element in stack -1 peek, size, empty
print(stack[-1])
print(len(stack))
print("isempty",bool(stack))

100
3
isempty True


through collection  , deque

In [25]:
from collections import deque
stack=deque()
stack.append(10)
stack.append(100)
stack.append(1000)
stack.append(10000)
for i in range(0,len(stack)):
    print(stack[i], end=" ")

stack.pop()
stack

10 100 1000 10000 

deque([10, 100, 1000])

through queue

In [24]:
from queue import LifoQueue
stack=LifoQueue(maxsize=4)

stack.put(12)
stack.put(22)
stack.put(122)
stack.put(1222)
print(stack)
stack.full()

True

TypeError: 'builtin_function_or_method' object is not subscriptable

In [31]:
#  similar to below  append pop
# stack=deque()
# list=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']

# same for updating
# stack=deque([12,32,43])
# def update(data, value):
#     idx=stack.index(data)
#     stack[idx]=value
#     return stack
# update(12,100)

stack=myarray.array('i', [12,31,54,80])

def update(data, value):
    for i in range(0, len(stack)):
        if stack[i]==data:
            stack[i]=value
            return stack
        
update(12,1000) 
    
            

array('i', [1000, 31, 54, 80])

In [47]:
list=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
stack=[]


for i in range(0, len(list)):
    stack.append(list[i])
    print(stack)
    
    
for i in range(0,len(list)):
    stack.pop()
    print(stack)    
    
    

['Sunday']
['Sunday', 'Monday']
['Sunday', 'Monday', 'Tuesday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday']
['Sunday', 'Monday', 'Tuesday', 'Wednesday']
['Sunday', 'Monday', 'Tuesday']
['Sunday', 'Monday']
['Sunday']
[]


In [21]:
stack=[12,87,90,65,45]

def update(data, value):
    for i in range(0, len(stack)):
        if stack[i]==data:
            stack[i]=value
            return stack
        
update(45,1000)    


#  or another approach    #

stack1= myarray.array('i',[12,32,78,98,12])

def update(data, value):
    idx=stack1.index(data)
    stack1[idx]=value
    for i in stack1:
        print(i, end=" ")
        
update(12,100)   
    
   
# or same approach but diggrent mechanisim

# stack[4]=1000
# print(stack)   

100 32 78 98 12 

In [2]:
import array as myarray

by arary using another approach that diff  little from  array

In [55]:
mystack=myarray.array('i',[1,2,3,4,5,6,7,8,9])
print(type(mystack))

for i in mystack:
    print(i, end=" ")
print('\n')  

mystack.append(10)  
for i in mystack:
    print(i, end=" ") 
print('\n')    
    

for i in range(0, len(mystack)):
    mystack.pop()
    for i in mystack:
        print(i, end=" ")
    print('\n')    
                

<class 'array.array'>
1 2 3 4 5 6 7 8 9 

1 2 3 4 5 6 7 8 9 10 

1 2 3 4 5 6 7 8 9 

1 2 3 4 5 6 7 8 

1 2 3 4 5 6 7 

1 2 3 4 5 6 

1 2 3 4 5 

1 2 3 4 

1 2 3 

1 2 

1 





In [37]:
#  sorting the stack in linkedlist form  trough list, array,deque

stack1=[102,32,67,90,32]
def sort_list():
    stack1.sort()
    return stack1

sort_list()


stack_deque=deque([80,65,2,10,7,35,92])
sample=[]

def sort_deue():
    for i in range(0, len(stack_deque)):
        x=stack_deque.pop()
        sample.append(x)
    sample.sort() 
    for i in sample:
        stack_deque.append(i)
    return stack_deque   
    
sort_deue()


stack_arr=myarray.array('i', [65,2,10,7,35])

sample1=[]
def sort_arr():
    for i in range(0, len(stack_arr)):
        x=stack_arr.pop()
        sample1.append(x)
    sample1.sort() 
    for i in sample1:
        stack_arr.append(i)
    return stack_arr  
    
sort_arr()    
    

array('i', [2, 7, 10, 35, 65])

In [23]:
class myname:
    x=10
    
p1=myname()
print(p1.x)    

10


youtube downloader

In [1]:
from pytube import YouTube
link="https://youtu.be/OKuiyX5k6zg"
ut=YouTube(link)
print(ut.title)
# print(ut.thumbnail_url)

PytubeError: Exception while accessing title of https://youtube.com/watch?v=OKuiyX5k6zg. Please file a bug report at https://github.com/pytube/pytube

text to handwriting

In [10]:
import pywhatkit as pw
txt=""" I'm ChatGPT, an AI assistant designed to help with a wide range of topics, from coding and troubleshooting to brainstorming and learning new concepts. I can assist with AWS security,
Python programming, and even creative writing. Whether you need technical guidance or just a casual chat,
I'm here to help! """

pw.text_to_handwriting(txt, "mouni.png")
print("End")


UnableToAccessApi: Unable to access Pywhatkit api right now

In [10]:
import qrcode as qr
img=qr.make("https://chatgpt.com/c/679f249b-4910-8009-84cc-5448ab861513")
img.save("email.png")

In [2]:
x='53'
y=4
print(x*y)

53535353


In [38]:
import qrcode 
from PIL import Image
import qrcode.constants
qr=qrcode.QRCode(version=1,error_correction=qrcode.constants.ERROR_CORRECT_H,box_size=10,border=3)
qr.add_data("https://github.com/interviewstreet")
qr.make(fit=True)
img=qr.make_image(fill_color="orange", back_color="blue")
img.save("git_hub.png")

In [11]:
x={12,32,45,3}
print(13 in x)

False


In [29]:
# append
x="Manasa"
y="Velpula"
# print(x+" "+y)
# x+=y
x
reverse="".join(reversed(x))
reverse



'asanaM'

In [ ]:
def func(**key):  # keyward arguments and positional arguments
    print(key['a'])
func(a="manasa", b="lalasa", c="mounis")    

manasa


In [33]:
import phonenumbers
from phonenumbers import timezone, geocoder,carrier
user=input("Enter a phone number +__: ")
phone=phonenumbers.parse(user)
time=timezone.time_zones_for_number(phone)
car=carrier.name_for_number(phone,"en")
go=geocoder.description_for_number(phone,"en")
print(phone)
print(time)
print(car)
print(go)

Country Code: 91 National Number: 7769892731
('Asia/Calcutta',)
Vodafone
India


In [56]:
# swapping
a=5
b=10
# a,b=b,a
# print(a,b)
a,b=[b,a]
print(a,b)
# temp=a
# a=b
# b=temp
# a,b
# a=a+b
# b=a-b
# a=a-b
# a,b
a=a^b
b=a^b
a=a^b
a,b

10 5


(5, 10)

In [61]:
#  tuples are imutable
a=(1,2,3)
b=(1,2,3)
print(f" idex is {id(a)}")
print(f" idex is {id(b)}")

print(a is b)
print(a==b)



 idex is 2032097511168
 idex is 2032097956032
False
True


In [62]:
# #  addresss is diff []
a=[1,2,3]
b=[1,2,3]
print(f" idex is {id(a)}")
print(f" idex is {id(b)}")

print(a is b)
print(a==b)

 idex is 2032097020608
 idex is 2032097024896
False
True


In [24]:
for _ in range(1,4):
    print("hello manasa")

hello manasa
hello manasa
hello manasa


(12, 10)

In [ ]:
a='Manasa'
# # print(a[::-1])
b=''

for char in a:
    print(char, end=" ")
    b
    

dec={"name":"manasa",
     "Age":20,
     "subject":"Maths",
     "urn":2022
    
}
print(dec)

# swapping keys to values and values to keys
dec_swap={}
for k,v in dec.items():
    print(k,v)
    dec_swap[v]=k
print(dec_swap)    



{'name': 'manasa', 'Age': 20, 'subject': 'Maths', 'urn': 2022}
name manasa
Age 20
subject Maths
urn 2022
{'manasa': 'name', 20: 'Age', 'Maths': 'subject', 2022: 'urn'}


In [9]:
class name:
    age=12
    gender="Female"
sub_name=name()


print(sub_name.age)
        
    

12


In [13]:
#palindrome number
a="malayalam"
reverse=a[::-1]

if(a==reverse):
    print("yes they are equal")
else:
    print("they are not reverse")    

yes they are equal


In [ ]:
a="manasa"
reverse=a[::-1]
print(reverse)

if(a==reverse):
    print("yse they are equal")
else:
    print("they are not equal")

asanam
asanam
they are not reverse


In [6]:
#string method
s="manasa velpula"
print(s.split())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.title())
print(s.capitalize())

['manasa', 'velpula']
manasa velpula
MANASA VELPULA
MANASA VELPULA
Manasa Velpula
Manasa velpula


In [20]:
sentence="The name odf your college is Ajeenkya Dy patil"
words=sentence.split()
print(words)
new_sentence=[]

for word in words:
    new_word=word[0].upper()+word[1:-1]+word[-1].lower()
    new_sentence.append(new_word)
    final_sen=" ".join(new_sentence)
print(final_sen)
    

['The', 'name', 'odf', 'your', 'college', 'is', 'Ajeenkya', 'Dy', 'patil']
The Name Odf Your College Is Ajeenkya Dy Patil


In [64]:
arr=[0,2,1,3,5,4,8,6,10]
n=len(arr)
total=n*(n+1)//2
res=total-sum(arr)
print("the missing number: " ,res)

the missing number:  6


In [ ]:
# list to str
lis=["Manasa", "laasa", "mounish"]
s=" ".join(lis)
print(type(s))

<class 'str'>


In [11]:
thisset = {"apple", "banana", "cherry",  0, 1,False, True}

print(thisset)

{0, 1, 'banana', 'apple', 'cherry'}


In [14]:
bank=10000.0
withdraw=float(input("enter  aamount"))
if withdraw > 0:
    
    
    if withdraw<=bank:
            bank-=withdraw
            print("transaction successful")
            print(f"available about is {bank}")
            
            
    else:
        print("insufficient balance")

    
else:
    print("invalid number") 

transaction successful
available about is 9894.95


In [73]:
n=5
for i in range(n,0,-1):
    print("* "*(n-i)+" "*(2*i-1))

         
*        
* *      
* * *    
* * * *  


In [79]:
n=5
for i in range(0,n+1):
    print(i*"* ")

n=5
for i in range(0,n+1):
    print("* "*(n-i)+" "*(2*i-1))   


* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * 
* * * *  
* * *    
* *      
*        
         
